name: fetch-meteo
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Show first lines of fetch_meteobahia.py
        run: |
          echo "=== HEAD fetch_meteobahia.py ==="
          nl -ba fetch_meteobahia.py | sed -n '1,30p'

      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - run: pip install pandas requests
      - run: pip install pandas requests openpyxl
      - name: Run fetch
        run: python fetch_meteobahia.py

      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: data
          force_orphan: true
